CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL UNIQUE,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	verifCode VARCHAR(255) NULL,
	verifCodeExpires TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	isActive BOOLEAN DEFAULT false,
	isComplete BOOLEAN DEFAULT false,
	cookieToken CHAR(64),
	cookieExpires DATETIME DEFAULT CURRENT_TIMESTAMP,
	lastOnline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE profiles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	gender VARCHAR(10) NOT NULL,
	preference VARCHAR(10) NOT NULL,
	birthdate DATE NOT NULL,
	bio VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	country VARCHAR(255) NOT NULL,
	lat DOUBLE NOT NULL,
	lon DOUBLE NOT NULL,
	primaryPicture VARCHAR(255) NOT NULL,
	secondaryPictureOne VARCHAR(255) NULL,
	secondaryPictureTwo VARCHAR(255) NULL,
	secondaryPictureThree VARCHAR(255) NULL,
	secondaryPictureFour VARCHAR(255) NULL,
	fame DECIMAL(5, 2) DEFAULT 0.00,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE history (
	id INT AUTO_INCREMENT PRIMARY KEY,
	host INT NOT NULL,
	visitor INT NOT NULL,
	FOREIGN KEY (host) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (visitor) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE likes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	target INT NOT NULL,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (target) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE blocks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	target INT NOT NULL,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (target) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE reports (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	target INT NOT NULL,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (target) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE interests (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE userInterests (
	userId INT NOT NULL,
	interestId INT NOT NULL,
	PRIMARY KEY (userId, interestId),
	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (interestId) REFERENCES interests(id) ON DELETE CASCADE
);

CREATE TABLE mailQueue (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	subject VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	sent BOOLEAN DEFAULT false,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
